name: genshintodaytalent
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  intl: ^0.17.0-nullsafety.2
  timezone:
  flutter_rating_bar: ^4.0.0-nullsafety.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - images/Diona.png
    - images/Diona_Banner.png
    - images/Kokomi.png
    - images/Kokomi_Banner.png
    - images/Eula.png
    - images/Eula_Banner.png
    - images/Xiangling.png
    - images/Xiangling_Banner.png
    - images/Xingqiu.png
    - images/Xingqiu_Banner.png
    - images/Shogun_Raiden.png
    - images/Shogun_Raiden_Banner.png
    - images/Ganyu.jpeg
    - images/Banner_Ganyu.png
    - images/Bennett.png
    - images/Banner_Bennett.png
    - images/Banner_Ayaka.png
    - images/Ayaka.png
    - images/Arataki_Itto.png
    - images/Banner_Arataki_Itto.png
    - images/Hu_Tao.png
    - images/Banner_Hu_Tao.png
    - images/Kazuha.png
    - images/Banner_Kazuha.png
    - images/Venti.png
    - images/Banner_Venti.png
    - images/Xiao.png
    - images/Banner_Xiao.png
    - images/Zhongli.jpeg
    - images/Banner_Zhongli.png
    - images/Albedo.jpeg
    - images/Banner_Albedo.png
    - images/Beidou.png
    - images/Banner_Beidou.png
    - images/Tartaglia.png
    - images/Banner_Tartaglia.png
    - images/Diluc.png
    - images/Banner_Diluc.png
    - images/Fischl.png
    - images/Banner_Fischl.png
    - images/Jean.png
    - images/Banner_Jean.png
    - images/Mona.png
    - images/Banner_Mona.png
    - images/Shenhe.png
    - images/Banner_Shenhe.png
    - images/Sucrose.png
    - images/Banner_Sucrose.png
    - images/Yae_Miko.png
    - images/Banner_Yae_Miko.png
    - images/Yoimiya.png
    - images/Banner_Yoimiya.png
    - images/Traveler_Electro.png
    - images/Banner_Traveler_Electro.png
    - images/Gorou.png
    - images/Banner_Gorou.png
    - images/Kaeya.png
    - images/Banner_Kaeya.png
    - images/Keqing.png
    - images/Banner_Keqing.png
    - images/Klee.png
    - images/Banner_Klee.png
    - images/Kujou_Sara.png
    - images/Banner_Kujou_Sara.png
    - images/Ningguang.png
    - images/Banner_Ningguang.png
    - images/Noelle.png
    - images/Banner_Noelle.png
    - images/Razor.png
    - images/Banner_Razor.png
    - images/Rosaria.png
    - images/Banner_Rosaria.png
    - images/Sayu.png
    - images/Banner_Sayu.png
    - images/Thoma.png
    - images/Banner_Thoma.png
    - images/Yanfei.png
    - images/Banner_Yanfei.png
    - images/Yun_Jin.png
    - images/Banner_Yun_Jin.png
    - images/Aloy.png
    - images/Banner_Aloy.png
    - images/Barbara.png
    - images/Banner_Barbara.png
    - images/Chongyun.png
    - images/Banner_Chongyun.png
    - images/Traveler_Geo.png
    - images/Banner_Traveler_Geo.png
    - images/Qiqi.png
    - images/Banner_Qiqi.png
    - images/Amber.png
    - images/Banner_Amber.png
    - images/Traveler_Anemo.png
    - images/Banner_Traveler_Anemo.png
    - images/Lisa.png
    - images/Banner_Lisa.png
    - images/Xinyan.png
    - images/Banner_Xinyan.png
    - images/Prototype_Amber.png
    - images/Prototype_Amber_Banner.png
    - images/Luxurious_Sea-Lord.png
    - images/Luxurious_Sea-Lord_Banner.png
    - images/Favonius_Sword.png
    - images/Favonius_Sword_Banner.png
    - images/Banner_Thundering_Pulse.png
    - images/Thundering_Pulse.jpeg
    - images/Skyward_Harp.png
    - images/Banner_Skyward_Harp.png
    - images/Polar_Star.jpeg
    - images/Banner_Polar_Star.jpg
    - images/Banner_Elegy_for_the_End.png
    - images/Elegy_for_the_End.png
    - images/Banner_Amos'_Bow.png
    - images/Amos'_Bow.png
    - images/The_Viridescent_Hunt.png
    - images/Banner_The_Viridescent_Hunt.png
    - images/Windblume_Ode.png
    - images/Banner_Windblume_Ode.png
    - images/Banner_The_Stringless.png
    - images/The_Stringless.png
    - images/Sacrifical_Bow.png
    - images/Banner_Sacrifical_Bow.png
    - images/Rust.png
    - images/Banner_Rust.png
    - images/Banner_Royal_Bow.png
    - images/Royal_Bow.png
    - images/Prototype_Crescent.png
    - images/Banner_Prototype_Crescent.png
    - images/Predator.jpeg
    - images/Banner_Predator.png
    - images/Mitternachts_Waltz.jpeg
    - images/Banner_Mitternachts_Waltz.png
    - images/Hamayumi.png
    - images/Banner_Hamayumi.png
    - images/Favonius_Warbow.png
    - images/Banner_Favonius_Warbow.png
    - images/Compound_Bow.png
    - images/Banner_Compound_Bow.png
    - images/Blackcliff_Warbow.png
    - images/Banner_Blackcliff_Warbow.png
    - images/Alley_Hunter.png
    - images/Banner_Alley_Hunter.png
    - images/Slingshot.png
    - images/Banner_Slingshot.png
    - images/Sharpshooter's_Oath.png
    - images/Banner_Sharpshooter's_Oath.png
    - images/Messenger.png
    - images/Banner_Messenger.png
    - images/Recurve_Bow.png
    - images/Banner_Recurve_Bow.png
    - images/Raven_Bow.png
    - images/Banner_Raven_Bow.png
    - images/Seasoned_Hunter's_Bow.png
    - images/Banner_Seasoned_Hunter's_Bow.png
    - images/Hunter's_Bow.png
    - images/Banner_Hunter's_Bow.png
    - images/Skyward_Atlas.png
    - images/Banner_Skyward_Atlas.png
    - images/Lost_Prayer_to_the_Sacred_Winds.png
    - images/Banner_Lost_Prayer_to_the_Sacred_Winds.png
    - images/Memory_Of_Dust.png
    - images/Banner_Memory_Of_Dust.png
    - images/Kagura's_Verity.jpeg
    - images/Banner_Kagura's_Verity.png
    - images/Everlasting_Moonglow.png
    - images/Banner_Everlasting_Moonglow.png
    - images/Wine_and_Song.png
    - images/Banner_Wine_and_Song.png
    - images/The_Widsith.png
    - images/Banner_The_Widsith.png
    - images/Solar_Pearl.png
    - images/Banner_Solar_Pearl.png
    - images/Sacrificial_Fragments.png
    - images/Banner_Sacrificial_Fragments.png
    - images/Royal_Grimoire.png
    - images/Banner_Royal_Grimoire.png
    - images/Oathsworn_Eye.png
    - images/Banner_Oathsworn_Eye.png
    - images/Mappa_Mare.png
    - images/Banner_Mappa_Mare.png
    - images/Hakushin_Ring.png
    - images/Banner_Hakushin_Ring.png
    - images/Frostbearer.png
    - images/Banner_Frostbearer.png
    - images/Favonius_Codex.png
    - images/Banner_Favonius_Codex.png
    - images/Eye_of_Perception.png
    - images/Banner_Eye_of_Perception.png
    - images/Dodoco_Tales.png
    - images/Banner_Dodoco_Tales.png
    - images/Blackcliff_Amulet.png
    - images/Banner_Blackcliff_Amulet.png
    - images/Twin_Nephrite.png
    - images/Banner_Twin_Nephrite.png
    - images/Thrilling_Tales_of_Dragon_Slayers.png
    - images/Banner_Thrilling_Tales_of_Dragon_Slayers.png
    - images/Otherworldly_Story.png
    - images/Banner_Otherworldly_Story.png
    - images/Magic_Guide.png
    - images/Banner_Magic_Guide.png
    - images/Emerald_Orb.png
    - images/Banner_Emerald_Orb.png
    - images/Pocket_Grimoire.png
    - images/Banner_Pocket_Grimoire.png
    - images/Apprentice's_Notes.png
    - images/Banner_Apprentice's_Notes.png
    - images/Wolf's_Gravestone.png
    - images/Banner_Wolf's_Gravestone.png
    - images/The_Unforged.png
    - images/Banner_The_Unforged.png
    - images/Song_of_Broken_Pines.png
    - images/Banner_Song_of_Broken_Pines.png
    - images/Skyward_Pride.png
    - images/Banner_Skyward_Pride.png
    - images/Redhorn_Stonethresher.png
    - images/Banner_Redhorn_Stonethresher.png
    - images/Whiteblind.png
    - images/Banner_Whiteblind.png
    - images/The_Bell.png
    - images/Banner_The_Bell.png
    - images/Snow-Tombed_Starsilver.png
    - images/Banner_Snow-Tombed_Starsilver.png
    - images/Serpent_Spine.png
    - images/Banner_Serpent_Spine.png
    - images/Sacrificial_Greatsword.png
    - images/Banner_Sacrificial_Greatsword.png
    - images/Royal_Greatsword.png
    - images/Banner_Royal_Greatsword.jpg
    - images/Rainslasher.png
    - images/Banner_Rainslasher.png
    - images/Prototype_Archaic.png
    - images/Banner_Prototype_Archaic.png
    - images/Katsuragikiri_Nagamasa.png
    - images/Banner_Katsuragikiri_Nagamasa.png
    - images/Favonius_Greatsword.png
    - images/Banner_Favonius_Greatsword.png
    - images/Blackcliff_Slasher.png
    - images/Banner_Blackcliff_Slasher.png
    - images/Akuoumaru.png
    - images/Banner_Akuoumaru.png
    - images/White_Iron_Greatsword.png
    - images/Banner_White_Iron_Greatsword.png
    - images/Skyrider_Greatsword.png
    - images/Banner_Skyrider_Greatsword.png
    - images/Ferrous_Shadow.png
    - images/Banner_Ferrous_Shadow.png
    - images/Debate_Club.png
    - images/Banner_Debate_Club.png
    - images/Bloodtainted_Greatsword.png
    - images/Banner_Bloodtainted_Greatsword.png
    - images/Old_Merc's_Pal.png
    - images/Banner_Old_Merc's_Pal.png
    - images/Waster_Greatsword.png
    - images/Banner_Waster_Greatsword.png
    - images/Vortex_Vanquisher.png
    - images/Banner_Vortex_Vanquisher.png
    - images/Staff_of_Homa.png
    - images/Banner_Staff_of_Homa.png
    - images/Skyward_Spine.png
    - images/Banner_Skyward_Spine.png
    - images/Primordial_Jade_Winged-Spear.png
    - images/Banner_Primordial_Jade_Winged-Spear.png
    - images/Engulfing_Lightning.png
    - images/Banner_Engulfing_Lightning.png
    - images/Calamity_Queller.png
    - images/Banner_Calamity_Queller.png
    - images/The_Catch.png
    - images/Banner_The_Catch.png
    - images/Royal_Spear.png
    - images/Banner_Royal_Spear.png
    - images/Prototype_Starglitter.png
    - images/Banner_Prototype_Starglitter.png
    - images/Lithic_Spear.png
    - images/Banner_Lithic_Spear.png
    - images/Lithic_Blade.png
    - images/Banner_Lithic_Blade.png
    - images/Kitain_Cross_Spear.png
    - images/Banner_Kitain_Cross_Spear.png
    - images/Favonius_Lance.png
    - images/Banner_Favonius_Lance.png
    - images/Dragon's_Bane.png
    - images/Banner_Dragon's_Bane.png
    - images/Dragonspine_Spear.png
    - images/Banner_Dragonspine_Spear.png
    - images/Deathmatch.png
    - images/Banner_Deathmatch.png
    - images/Crescent_Pike.png
    - images/Banner_Crescent_Pike.png
    - images/Blackcliff_Pole.png
    - images/Banner_Blackcliff_Pole.png
    - images/White_Tassel.png
    - images/Banner_White_Tassel.png
    - images/Halberd.png
    - images/Banner_Halberd.png
    - images/Black_Tassel.png
    - images/Banner_Black_Tassel.png
    - images/Iron_Point.png
    - images/Banner_Iron_Point.png
    - images/Beginner's_Protector.png
    - images/Banner_Beginner's_Protector.png
    - images/Summit_Shaper.png
    - images/Banner_Summit_Shaper.jpg
    - images/Skyward_Blade.png
    - images/Banner_Skyward_Blade.png
    - images/Primordial_Jade_Cutter.png
    - images/Banner_Primordial_Jade_Cutter.png
    - images/Mistsplitter_Reforged.png
    - images/Banner_Mistsplitter_Reforged.png
    - images/Haran_Geppaku_Futsu.png
    - images/Banner_Haran_Geppaku_Futsu.png
    - images/Freedom-Sworn.png
    - images/Banner_Freedom-Sworn.png
    - images/Aquila_Favonia.png
    - images/Banner_Aquila_Favonia.png
    - images/The_Flute.png
    - images/Banner_The_Flute.png
    - images/The_Black_Sword.png
    - images/Banner_The_Black_Sword.png
    - images/The_Alley_Flash.png
    - images/Banner_The_Alley_Flash.png
    - images/Sword_of_Descension.jpeg
    - images/Banner_Sword_of_Descension.png
    - images/Sacrificial_Sword.png
    - images/Banner_Sacrificial_Sword.png
    - images/Royal_Longsword.jpeg
    - images/Banner_Royal_Longsword.png
    - images/Prototype_Rancour.png
    - images/Banner_Prototype_Rancour.png
    - images/Lion's_Roar.png
    - images/Banner_Lion's_Roar.png
    - images/Iron_Sting.png
    - images/Banner_Iron_Sting.png
    - images/Festering_Desire.png
    - images/Banner_Festering_Desire.png
    - images/Cinnabar_Spindle.jpeg
    - images/Banner_Cinnabar_Spindle.png
    - images/Blackcliff_Longsword.png
    - images/Banner_Blackcliff_Longsword.png
    - images/Amenoma_Kageuchi.png
    - images/Banner_Amenoma_Kageuchi.png
    - images/Traveler's_Handy_Sword.png
    - images/Banner_Traveler's_Handy_Sword.png
    - images/Banner_Skyrider_Sword.png
    - images/Skyrider_Sword.png
    - images/Harbinger_of_Dawn.png
    - images/Banner_Harbinger_of_Dawn.png
    - images/Fillet_Blade.png
    - images/Banner_Fillet_Blade.png
    - images/Dark_Iron_Sword.png
    - images/Banner_Dark_Iron_Sword.png
    - images/Cool_Steel.png
    - images/Banner_Cool_Steel.png
    - images/Dull_Blade.png
    - images/Banner_Dull_Blade.png
    - images/Silver_Sword.png
    - images/Banner_Silver_Sword.png
    - images/Ayato.png
    - images/Banner_Ayato.png
    - images/Scattered_Piece_Of_Decarabian's_Dream.png
    - images/Scattered_Piece_Of_Decarabian's_Dream_Location.jpg
    - images/Mist_Veiled_Primo_Elixir.png
    - images/Mist_Veiled_Primo_Elixir_Location.jpg
    - images/Chunk_Of_Aerosiderite.png
    - images/Chunk_Of_Aerosiderite_Location.jpg
    - images/Prototype_Amber.png
    - images/Logo.png
    - assets/characters.json
    - assets/talents.json
    - images/Talent_Ballad.jpeg
    - images/Talent_Diligence.jpeg
    - images/Talent_Elegance.jpeg
    - images/Talent_Freedom.jpeg
    - images/Talent_Gold.jpeg
    - images/Talent_Light.jpeg
    - images/Talent_Prosperity.jpeg
    - images/Talent_Resistance.jpeg
    - images/Talent_Transience.jpeg
    - images/Location_Talent_Forsaken_Rifted.jpg
    - images/Location_Talent_Taishan_Mansion.jpg
    - images/Location_Talent_Violet_Court.jpg
    - images/Wallpaper.jpg
    - images/Dream_Of_The_Dandelion_Gladiator.png
    - images/Boreal_Wolfs_Nostalgia.png
    - images/Location_Submerged_Valley.jpg
    - images/Divine_Body_From_Guyun_Location.png
    - images/Golden_Branch_Of_a_Distant_Sea.png
    - images/Location_Sand_Burial.jpg
    - images/Narukamis_Valor.png
    - images/Mask_Of_The_Kijin.png
    - images/Yelan_Banner.png
    - images/Yelan.png
    - images/Kuki_Shinobu.jpg
    - images/Banner_Kuki_Shinobu.png
    - images/Banner_Fading_Twilight.png
    - images/Fading_Twilight.png
    - images/Aqua_Simulacra.png
    - images/Banner_Aqua_Simulacra.png
    - images/Philosophie_Of_Ingenuity.png
    - images/Lower_Ground_Of_Chatrakam_Cave_Area.jpg
    - images/Philosophies_Of_Admonition.png
    - images/Philosophies_Of_Praxis.png
    - images/Tower_Of_Abject_Pride.jpg
    - images/Golden_Talisman_of_the_Forest_Dew.png
    - images/Oasis_Gardenâ€™s_Truth.png
    - images/Olden_Days_of_Scorching_Might.png
    - images/Heizou.png
    - images/Banner_Heizou.png
    - images/Tighnari.png
    - images/Banner_Tighnari.png
    - images/Collei.png
    - images/Banner_Collei.png
    - images/Dori.png
    - images/Banner_Dori.png
    - images/Forest_Regalia.png
    - images/Banner_Forest_Regalia.png
    - images/Sapwood_Blade.png
    - images/Banner_Sapwood_Blade.png
    - images/King's_Squire.png
    - images/Banner_King's_Squire.png
    - images/Moonpiercer.png
    - images/Banner_Moonpiercer.png
    - images/Fruit_of_Fulfillment.png
    - images/Banner_Fruit_of_Fulfillment.png
    - images/Hunter's_Path.png
    - images/Banner_Hunter's_Path.png
    - images/End_Of_The_Line.png
    - images/Banner_End_Of_The_Line.png
    - images/Cyno.png
    - images/Banner_Cyno.png
    - images/Candace.png
    - images/Banner_Candace.png
    - images/Nilou.png
    - images/Banner_Nilou.png
    - images/Key_Of_Khaj-Nisut.png
    - images/Banner_Key_Of_Khaj-Nisut.png
    - images/Staff_Of_The_Scarlet_Sands.png
    - images/Banner_Staff_Of_The_Scarlet_Sands.png
    - images/Makhaira_Aquamarine.png
    - images/Banner_Makhaira_Aquamarine.png
    - images/Wandering_Evenstar.png
    - images/Banner_Wandering_Evenstar.png
    - images/Xiphos'_Moonlight.png
    - images/Banner_Xiphos'_Moonlight.png
    - images/Missive_Windspear.png
    - images/Banner_Missive_Windspear.png
    - images/Nahida.png
    - images/Banner_Nahida.png
    - images/Layla.png
    - images/Banner_Layla.png
    - images/A_Thousand_Floating_Dreams.png
    - images/Banner_A_Thousand_Floating_Dreams.png
    - images/Wanderer.png
    - images/Banner_Wanderer.png
    - images/Faruzan.png
    - images/Banner_Faruzan.png
    - images/Tulaytullah's_Remembrance.png
    - images/Banner_Tulaytullah's_Remembrance.png
    - images/Toukabou_Shigure.png
    - images/Banner_Toukabou_Shigure.png
    - images/Alhaitham.png
    - images/Banner_Alhaitham.png
    - images/Yaoyao.png
    - images/Banner_Yaoyao.png
    - images/Light_Of_Foliar_Incision.png
    - images/Banner_Light_Of_Foliar_Incision.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
